name: GitHub Classroom Workflow

on: [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/setup-maven-action@v1.6.0
        with:
            java-version: '11'
            maven-version: '3.9.0'
      - uses: education/autograding@v1